src/Entity/Program.php
<?php

namespace App\Entity;

use App\Repository\ProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProgramRepository::class)]
class Program
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150, unique: true)]
    private ?string $code = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_end = null;

    #[ORM\ManyToOne(inversedBy: 'programs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Headquarter $headquarter = null;

    #[ORM\OneToMany(targetEntity: Document::class, mappedBy: 'program')]
    private Collection $documents;

    #[ORM\OneToMany(targetEntity: PersonInProgram::class, mappedBy: 'program')]
    private Collection $people;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
        $this->people = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): static
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): static
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getHeadquarter(): ?Headquarter
    {
        return $this->headquarter;
    }

    public function setHeadquarter(?Headquarter $headquarter): static
    {
        $this->headquarter = $headquarter;

        return $this;
    }

    /**
     * @return Collection<int, Document>
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): static
    {
        if (!$this->documents->contains($document)) {
            $this->documents->add($document);
            $document->setProgram($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): static
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getProgram() === $this) {
                $document->setProgram(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PersonInProgram>
     */
    public function getPeople(): Collection
    {
        return $this->people;
    }

    public function addPeople(PersonInProgram $personInProgram): static
    {
        if (!$this->people->contains($personInProgram)) {
            $this->people->add($personInProgram);
            $personInProgram->setProgram($this);
        }

        return $this;
    }

    public function removePeople(PersonInProgram $personInProgram): static
    {
        if ($this->people->removeElement($personInProgram)) {
            // set the owning side to null (unless already changed)
            if ($personInProgram->getProgram() === $this) {
                $personInProgram->setProgram(null);
            }
        }

        return $this;
    }

    public function isActived()
    {
        $now = new \DateTime('NOW');

        if ($now < $this->getDateEnd()) {
            return true;
        }
        return false;
    }
}

src/Controller/Report/GenerateController.php
<?php

namespace App\Controller\Report;

use App\Filter\ReportFiler;
use App\Form\Filter\ReportFilterType;
use App\Repository\PersonInProgramRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class GenerateController extends AbstractController
{
    #[Route('/report/admin', name: 'app_report_admin')]
    public function report(
        PersonInProgramRepository $repository,
        Request $request
    ): Response {
        $reportFilter = new ReportFiler();

        $form = $this->createForm(ReportFilterType::class, $reportFilter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $filter = $form->getData();

            $dataPersonProgram = $repository->getDataByFilter($filter);
            
            return $this->render('report/result.html.twig', [
                'personinprogram' => $dataPersonProgram
            ]);
        } else if ($form->isSubmitted()) {
            $this->addFlash('danger', 'Los campos fechas no son válidos');
        }

        return $this->render('report/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/report/index.html.twig
{% extends 'app.html.twig' %}

{% block title %}Infomres{% endblock %}

{% block content %}
 <div class="row page-titles">
    <div class="col-md-7 col-12 align-self-center">
        <h3 class="text-themecolor mb-0">Informes</h3>
        </h6>
    </div>
</div>
 <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Generar Informe</h4>
                    {{ form_start(form) }}
                        <div class="form-floating mb-3">
                                {{ form_widget(form.dateStart, {'attr': {'class': 'form-control'}}) }}
                                <label>                        
                                    {{ form_label(form.dateStart) }}
                                </label>
                                {{ form_errors(form.dateStart) }}
                        </div>
                        <div class="form-floating mb-3">
                                {{ form_widget(form.dateEnd, {'attr': {'class': 'form-control'}}) }}
                                <label>                        
                                    {{ form_label(form.dateEnd) }}
                                </label>
                                {{ form_errors(form.dateEnd) }}
                        </div>
                        <div class="form-floating mb-3">
                                {{ form_widget(form.program, {'attr': {'class': 'select2 form-select'}}) }}
                                {{ form_label(form.program) }}
                                <small class="form-control-feedback text-danger">
                                    {{ form_errors(form.program) }}
                                </small>
                        </div>                        
                        <div class="d-md-flex align-items-center">                      
                            <div class="mt-3 mt-md-0 ms-auto">
                                {{  form_row(form.save, {'attr': {'class': 'btn btn-info font-weight-medium rounded-pill px-4'}}) }}
                            </div>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/report/result.html.twig
{% extends 'app.html.twig' %}

{% block title %}Ver Informe{% endblock %}

{% block content %}
 <div class="row page-titles">
    <div class="col-md-7 col-12 align-self-center">
        <h3 class="text-themecolor mb-0">Ver Infome</h3>        
    </div>
</div>
 <div class="container-fluid">
    <div class="row">
            <div class="col-12 text-end d-flex justify-content-md-end justify-content-center">
                <div class="row button-group">
                    <a href="{{ path('app_report_admin') }}" title="Generar Informes">                
                        <button type="button" class="justify-content-center w-100 btn btn-rounded btn-info d-flex align-items-center">                      
                            <i data-feather="arrow-left" class="feather-sm fill-white me-2"></i>Volver
                        </button>   
                    </a>                 
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title"></h4>
                    <div class="table-responsive table-responsive-document">
                        <table id="datatable-reports" class="table dataTable display table-bordered table-striped no-wrap">
                            <thead>
                                <tr>
                                    <th>Cod. Prg.</th>
                                    <th>Sede</th>
                                    <th>Nombre y Apellidos</th>
                                    <th>NIF</th>
                                    <th>Sexo</th>
                                    <th>F.Nacimiento</th>
                                    <th>Edad</th>
                                    <th>Nacionalidad</th>
                                    <th>Dirección</th>
                                    <th>Teléfono</th>
                                    <th>Adicción prinicipal</th>
                                    <th>Tipo</th>
                                    <th>F.Inicio</th>
                                    <th>F.Fin</th>
                                    <th>IRPF</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if personinprogram is defined and personinprogram|length > 0%}
                                    {% for personinprogram in personinprogram %}
                                        {% set age = (null != personinprogram.person.birthdate) ? date().diff(date(personinprogram.person.birthdate)).y : '---'%}
                                        {% set totalTimetable = personinprogram.timetables|length - 1 %}
                                        {% set dateStart = personinprogram.timetables[0].dateStart|date('d/m/Y') %}    
                                        {% set dateEnd = (personinprogram.timetables[totalTimetable].dateEnd is null) ? '--' : personinprogram.timetables[totalTimetable].dateEnd|date('d/m/Y') %}
                                        <tr>
                                            <td>{{ personinprogram.program.code}}</td>
                                            <td>{{ personinprogram.program.headquarter.name}}</td>
                                            <td>{{ personinprogram.person.lastname ~ ', ' ~ personinprogram.person.name }}</td>
                                            <td>{{ personinprogram.person.nif }}</td>
                                            <td>{{ (null != personinprogram.person.gender) ? personinprogram.person.gender|trans({}, 'app') : '---' }}</td>
                                            <td>{{ (null != personinprogram.person.birthdate) ? personinprogram.person.birthdate|date('d/m/Y') : '---' }}</td>
                                            <td>{{ age }}</td>
                                            <td>{{ (null != personinprogram.person.nationality) ? personinprogram.person.nationality : '---' }}</td>
                                            <td>{{ (null != personinprogram.person.address) ? personinprogram.person.address : '---' }}</td>
                                            <td>{{ (personinprogram.person.phone is null) ? '---' : personinprogram.person.phone }}</td>
                                            <td>{{ (null != personinprogram.person.drug) ? personinprogram.person.drug.name : '---' }}</td>
                                            <td>{{ personinprogram.person.type|trans({}, 'app')  }}</td>
                                            <td>{{ dateStart }}</td>
                                            <td>{{ dateEnd }}</td>
                                            <td>{{ (null != personinprogram.reductIrpf and personinprogram.reductIrpf) ? 'Sí' : 'No'}}</td>
                                        </tr>
                                    {% endfor %}

                                {% else %}
                                    <tr><td colspan="15">No existen registros a mostrar con dichos filtros</td></tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer_javascripts %}
    {{ parent() }} 
    <script src="{{ asset('dist/libs/datatables.net/js/buttons.html5.min.js') }}"></script> 
    <script src="{{ asset('dist/libs/datatables.net/js/buttons.print.min.js') }}"></script> 
    <script src="{{ asset('dist/libs/datatables.net/js/dataTables.buttons.min.js') }}"></script> 

    {% if personinprogram is defined  and personinprogram|length > 0 %}
        <script type="text/javascript">
          jQuery( document ).ready(function () {
              if (jQuery('#datatable-reports').length > 0 ){                            
                  jQuery("#datatable-reports").DataTable({
                      responsive: true,
                      autoFill: true,
                      fixedHeader: true,
                      scrollX: true,
                      language: {
                        url: "{{ asset('dist/js/datatables_i18n_es-ES.json') }}"
                      },
                     dom: "Bfrtip",
                     buttons: ["csv", "excel","print"],
                  });
                  
                  var waitForEl = function(selector, callback) {
                    if (jQuery(selector).length) {
                            callback();
                    } else {
                        setTimeout(function() {
                        waitForEl(selector, callback);
                        }, 100);
                    }
                  };

                  waitForEl(".dt-buttons > button.dt-button", function() {
                      jQuery(".dt-buttons > button.dt-button").addClass("btn btn-info mr-1");
                  });
              }    
          });
        </script>   
    {% endif %}     
  {% endblock %}